### ISSUE TITLE
How to extract features for mp4 videos?

### ISSUE THREAD

**Issue by vectoros** [jarikorhonen/nr-vqa-consumervideo#1]
I found that the code is just used for extracting features for YUV videos. And, it is difficult for me to achieve the code to extract features for mp4 videos. Could you provide the code how to extract features for mp4 videos? Thank you very much!

**Comment by jarikorhonen** [comment]
The code is for raw video, and MP4 is a compressed video format. You need to decompress MP4 videos to obtain YUV. You can use some free software, e.g. FFmpeg (https://www.ffmpeg.org/) for that purpose.
