### ISSUE TITLE
Could you share qualcommSubjectiveData.mat used in compute_features_example.m?

### ISSUE THREAD

**Issue by weidelongdongqiang** [jarikorhonen/nr-vqa-consumervideo#10]
The MOS values in qualcommSubjectiveData.mat is very important to train a SVR model.

**Comment by jarikorhonen** [comment]
Ok, it is [here now](https://github.com/jarikorhonen/nr-vqa-consumervideo/blob/6d182872561ab9d816ee422777290086af5568c2/qualcommSubjectiveData.mat).
