### ISSUE TITLE
Performance on CVD2014 dataset

### ISSUE THREAD

**Issue by zhenshan0127** [jarikorhonen/nr-vqa-consumervideo#11]
Hello, 

I try to reproduce the results on CVD2014 dataset. But, the below results are very different from the original article:

Average results
PLCC:  0.7496275698465809 ( std: 0.055980627599043604 )
SRCC:  0.7390059003531806 ( std: 0.05983049266763412 )
RMSE:  14.166097250296001 ( std: 1.5840549600189715 )

I am not sure if I use realignment MOS correctly. Could you please give me some suggestions?

Thank you for your time!

**Comment by jarikorhonen** [comment]
Hello, are you sure you are using the realigned scores? This result looks more like those you can get if using the raw MOS scores.

**Comment by zhenshan0127** [comment]
Thank you for reply!
These are some examples in Realignment MOS:
Content;File_name;Original   MOS;Realignment MOS;;;; |
City;Test01_City_D01;71 17;67 29;;;;
City;Test01_City_D02;25 83;24 86;;;;
City;Test01_City_D03;18 45;17 96;;;;
City;Test01_City_D04;31 57;30 23;;;;
City;Test01_City_D05;26 07;25 08;;;;
City;Test01_City_D06;46 05;43 78;;;;
City;Test01_City_D07;54 48;51 67;;;;
City;Test01_City_D08;67 32;63 68;;;;
City;Test01_City_D09;68 67;64 95;;;;
Talking head;Test01_Talking_Head_D01;70 18;69 37;;;;
Talking head;Test01_Talking_Head_D02;25 43;31 65;;;;

Could you please me give me some ideas to use the correct MOS?

**Comment by jarikorhonen** [comment]
The format is a bit strange. The first line (file Test01_City_D01) original MOS is 71.17, realignment MOS is 67.29. The second line (file Test01_City_D02) original MOS is 25.83, and realignment MOS 24.86. 

You may need to use "find and replace" function in text editor to change the delimiters so that the file can be read as standard CSV file. For example replacing first "," with ".", and then ";" with","

**Comment by zhenshan0127** [comment]
Thank you for suggestions.

I try your method to get realignment MOS, but the results are these:
Average results
PLCC:  0.7701793480327578 ( std: 0.05556790022799991 )
SRCC:  0.7641438210002718 ( std: 0.06013789749728708 )
RMSE:  13.770616900202477 ( std: 1.4712191904523526 )

And, I can get the almost same results on KONVID-1K and LIVE-QUALCOMM as the paper. So, I am confused. Could you please provide the features of CVD2014? I can compare it with mine.

Thank you for your time.

**Comment by jarikorhonen** [comment]
I tried to find the feature file but couldn't find it, as I have only stored it in my old computer not in use any more. Unfortunately I don't have time to reproduce those right now. You could check if you are using the right hyperparameters for SVM, it can make a rather big difference in the results. The used hyperparameters for different datasets should be in the paper.

**Comment by zhenshan0127** [comment]
Thank you for reply!

I have tried different hyperparameters. I think there maybe some problems in the processing of .avi video files (format of CVD2014) that cause the extracted features to be biased. 

Thank you again for your suggestions!
