### ISSUE TITLE
A question for the code

### ISSUE THREAD

**Issue by ChairManMeow-SY** [jarikorhonen/nr-vqa-consumervideo#12]
Hi Jari,  I read the code and can not understand the code for best MV search.

As decribed in the paper section 3.b, a 3x3 block around the key pixels is used to search the best matched block within a serching range (radius should be 480/40=12 pixels). 

But in the code, a 3x3 block around the key pixel is extracted. For each pixel in the block, the difference between previous block and the current pixel value is calculated. The summed difference then decides the final estimated motion vector.

```
        for i=-1:1
            for j=-1:1
                if i~=0 || j~=0
                    diff_win_prev(3:end-2,3:end-2) = ...
                        diff_win_prev(3:end-2,3:end-2) + ...
                        (sob_v_this(tar_y+i, tar_x+j)- ...
                          surr_win_v_prev(3+i:end-2+i,3+j:end-2+j)).^2+ ...
                        (sob_h_this(tar_y+i, tar_x+j)- ...
                          surr_win_h_prev(3+i:end-2+i,3+j:end-2+j)).^2;   
                    diff_win_next(3:end-2,3:end-2) = ...
                        diff_win_next(3:end-2,3:end-2) + ...
                        (sob_v_this(tar_y+i, tar_x+j)- ...
                          surr_win_v_next(3+i:end-2+i,3+j:end-2+j)).^2+...
                        (sob_h_this(tar_y+i, tar_x+j)- ...
                        surr_win_h_next(3+i:end-2+i,3+j:end-2+j)).^2;   
                end
            end
```

Is this an approximation way for the block searching? I'm confused with the code..

**Comment by jarikorhonen** [comment]
Hi Oldog, this part of the code is about computing the differences between Sobel filtered versions of two consecutive frames. The key pixels are those pixels where the difference between 3x3 pixel blocks of the Sobel filtered versions of the frame n and frame n-1 (diff_win_prev) or frame n+1 (diff_win_next) are the largest. 

Block searching for 3x3 pixel blocks is in lines 355-380 backwards and 382-407 forwards.

**Comment by ChairManMeow-SY** [comment]
Thanks for the reply~

Thus the key pixel is obtained with a 2-step selection: 
1. Points have max Corner value within a window whose radius is bl_size.
2. Points around pixels in step.1 that have largest difference between sobel filtered ajacent frames.

Is that right?

**Comment by jarikorhonen** [comment]
Sorry, my answer was maybe a bit inaccurate. Key pixels are found in lines 248-285. This is the first step. Then there is a loop going through all the key pixels, from line 308 to 434. Loop in 331-348 computes a matrix with similarity of the key pixel and the pixels in the previous and following frame. The code in lines 355-380 and 382-407 has some additional conditions to select the smallest differences (with some constraints) to derive the motion vectors.

**Comment by ChairManMeow-SY** [comment]
Oh I see. Thank you for your kind help.. 

I'm trying to re-implement it with pytorch.

Here is a little problem in line 366:

https://github.com/jarikorhonen/nr-vqa-consumervideo/blob/6d182872561ab9d816ee422777290086af5568c2/compute_nrvqa_features.m#L355-L380

In my understanding the backward MV is extracted here, so should the line 366 be:

```
if diff_win_prev(idx(idx2(1)))<1.1*sorted(1)
    min_diff = diff_win_prev(idx(idx2(1)));
```

**Comment by jarikorhonen** [comment]
Yes, you are right, it is a bug.
