### ISSUE TITLE
Question about Performance Comparison details

### ISSUE THREAD

**Issue by stillbetter** [jarikorhonen/nr-vqa-consumervideo#5]
Hi Dr.Korhonen:

I found you compared NIQE and V-BLIINDS(needs NIQE).

I wonder, when you conducted Performance Comparison, if you tested with the default setting (_125 pristine images with patch size set to 96X96 and sharpness threshold of 0.75_ as the official NIQE released version) or you retrained and got new  parameters for both NIQE and VBLIINDS?

Thanks!

**Comment by jarikorhonen** [comment]
I re-trained them using the same training and testing sets for every model (I think this the most fair method). One frame per second was sampled from the video sequences and used for training.

**Comment by stillbetter** [comment]
Sorry Doctor, I guess I didn't make myself understood. I'm asking about the NIQE parameter. It's also used in V-BLIINDS as feature 1 to 36.

NIQE just computes the distance of the distorted NSS and the NATURAL NSS which released in the official code. It's the 'modelparameters.mat' in NIQE and 'frames_modelparameters.mat' in VBLIINDS's released code.

My question is whether you use the default parameter or you choose some frames as natural ones and rebuild the model parameter(Not the SVR parameters).

**Comment by jarikorhonen** [comment]
Ok, I see. I have used the default parameters.

**Comment by stillbetter** [comment]
That's it! Thanks Doctor!
