### ISSUE TITLE
The best parament of LIVE-VQC

### ISSUE THREAD

**Issue by liu0527aa** [jarikorhonen/nr-vqa-consumervideo#6]
Hello，I want to comapre my method with the TLVQM and CNN+TLVQM. However, I found that you don‘t show the SVR parament setting of LIVE-VQC. So I use the parament of LIVE-Qualcomm as the parament of LIVE-VQC. But the result are different from the paper of ACMMM. Can you tell me the best parament of LIVE-VQC?

**Comment by jarikorhonen** [comment]
Hello, in ACM MM study I did not use the parameters from the original study, instead I was using the Matlab script with automatic hyperparameter optimization. You can see lines 38-52 in this file as a model: https://github.com/jarikorhonen/cnn-tlvqm/blob/master/predictMOSwithSVR.m.
